### ISSUE TITLE
Error that no one can seem to fix...

### ISSUE THREAD

**Issue by howardemilya** [learn-co-curriculum/js-ajax-intro-to-ajax-readme#10]
0 passing (31ms)
  1 failing

  1) index "before all" hook:
     Error: Cannot find module 'jsdom/lib/old-api'
      at require (internal/module.js:20:19)
      at Context.<anonymous> (node_modules/mocha-jsdom/index.js:53:5)

npm ERR! Test failed.  See above for more details.

Someone mentioned trying to change the "mocha-jsdom": "^1.1.0" in package.json to "~" instead of "^" and running npm install... but when you do that it only changes the error to the following:

1) index "before all" hook:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at Object.done (node_modules/mocha-jsdom/index.js:70:7)
      at process.nextTick (node_modules/jsdom/lib/jsdom.js:325:18)
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickCallback (internal/process/next_tick.js:104:9)

Please help!

**Comment by drakeltheryuujin** [comment]
Hi @howardemilya,

This lesson has been rewritten as more of a code along. The issues that you were previously facing should be remedied. 

Thank you for your feedback!
